import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_overlay_window/flutter_overlay_window.dart';
import 'package:url_launcher/url_launcher.dart';
import '../core/theme.dart';
import '../models/project.dart';
import '../services/github_service.dart';
import '../services/termux_service.dart';
import '../widgets/mascot.dart';
import 'project_detail.dart';

const coucouPort=8765;
class Dashboard extends StatefulWidget{const Dashboard({super.key});@override State<Dashboard> createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{
  final github=GitHubService(),termux=TermuxService(); HttpServer? server; StreamSubscription? overlaySub;
  List<ProjectRepo> projects=[]; bool loading=true,termuxOnline=false,overlayActive=false,hasToken=false; int tab=0; String search=''; CoucouState state=CoucouState.idle;
  @override void initState(){super.initState();_init();}
  Future<void> _init() async{overlaySub=FlutterOverlayWindow.overlayListener.listen((e){if(e is String){final s=stateFromString(e);if(s!=null&&mounted)setState(()=>state=s);}});await _startBridge();await _refresh();}
  Future<void> _startBridge() async{server=await HttpServer.bind(InternetAddress.loopbackIPv4,coucouPort);server!.listen((q)async{q.response.headers.contentType=ContentType.json;if(q.uri.path=='/ping'){q.response.write(jsonEncode({'ok':true,'service':'coucou-android','port':coucouPort}));}else if(q.uri.path=='/state'){final s=stateFromString(q.uri.queryParameters['value']??'');if(s==null){q.response.statusCode=400;}else{await _setState(s);q.response.write(jsonEncode({'ok':true,'state':s.name}));}}else{q.response.statusCode=404;}await q.response.close();});}
  Future<void> _refresh() async{if(mounted)setState(()=>loading=true);try{final list=await github.loadProjects();final tok=await github.readToken();final tx=await termux.ping();final ov=await FlutterOverlayWindow.isActive();if(mounted)setState((){projects=list;hasToken=tok!=null&&tok.isNotEmpty;termuxOnline=tx;overlayActive=ov;loading=false;});}catch(e){if(mounted)setState(()=>loading=false);_msg(e.toString(),true);}}
  Future<void> _setState(CoucouState s)async{if(mounted)setState(()=>state=s);if(await FlutterOverlayWindow.isActive())await FlutterOverlayWindow.shareData(s.name);}
  Future<void> _toggleOverlay()async{if(overlayActive){await FlutterOverlayWindow.closeOverlay();}else{if(!await FlutterOverlayWindow.isPermissionGranted())await FlutterOverlayWindow.requestPermission();if(await FlutterOverlayWindow.isPermissionGranted()){await FlutterOverlayWindow.showOverlay(height:190,width:360,alignment:OverlayAlignment.topCenter,flag:OverlayFlag.defaultFlag,enableDrag:true,positionGravity:PositionGravity.auto,overlayTitle:'Coucou Projects Hub',overlayContent:'GitHub + Termux ativo',visibility:NotificationVisibility.visibilityPublic);await Future.delayed(const Duration(milliseconds:400));await FlutterOverlayWindow.shareData(state.name);}}await _refresh();}
  void _msg(String t,bool e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t),backgroundColor:e?AppColors.red:AppColors.surface));
  void _detail(ProjectRepo p)=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ProjectDetail(repo:p,github:github,termux:termux,termuxOnline:termuxOnline)));
  Future<void> _open(String u)async{final x=Uri.tryParse(u);if(x!=null)await launchUrl(x,mode:LaunchMode.externalApplication);}
  List<ProjectRepo> get shown=>projects.where((p)=>p.name.toLowerCase().contains(search.toLowerCase())||p.description.toLowerCase().contains(search.toLowerCase())).toList();
  @override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Coucou Projects Hub',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:_refresh,icon:const Icon(Icons.refresh))]),body:IndexedStack(index:tab,children:[_home(),_projects(),_apks(),_sites(),_settings()]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Início'),NavigationDestination(icon:Icon(Icons.folder_outlined),selectedIcon:Icon(Icons.folder),label:'Projetos'),NavigationDestination(icon:Icon(Icons.android_outlined),selectedIcon:Icon(Icons.android),label:'APKs'),NavigationDestination(icon:Icon(Icons.public_outlined),selectedIcon:Icon(Icons.public),label:'Sites'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Ajustes')]));}
  Widget _home()=>RefreshIndicator(onRefresh:_refresh,child:ListView(padding:const EdgeInsets.all(18),children:[ClipRRect(borderRadius:BorderRadius.circular(24),child:Image.asset('assets/brand/logo.jpg')),const SizedBox(height:16),Row(children:[MascotImage(state:state,size:86),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(state.label,style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:state.color)),Text('${projects.length} projetos sincronizados',style:const TextStyle(color:AppColors.muted))]))]),const SizedBox(height:16),Row(children:[Expanded(child:_stat('GitHub',hasToken?'Público + privado':'Somente público',hasToken?AppColors.green:AppColors.amber)),const SizedBox(width:10),Expanded(child:_stat('Termux',termuxOnline?'Online':'Offline',termuxOnline?AppColors.green:AppColors.red))]),const SizedBox(height:10),_stat('Mascote',overlayActive?'Flutuando':'Desligado',overlayActive?AppColors.cyan:AppColors.muted),const SizedBox(height:12),FilledButton.icon(onPressed:_toggleOverlay,icon:Icon(overlayActive?Icons.close:Icons.bubble_chart),label:Text(overlayActive?'Fechar mascote':'Mostrar mascote flutuante')),const SizedBox(height:22),const Text('Recentes',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),...projects.take(6).map((p)=>Card(child:ListTile(onTap:()=>_detail(p),leading:CircleAvatar(backgroundImage:NetworkImage(p.ownerAvatar)),title:Text(p.name),subtitle:Text(p.language),trailing:const Icon(Icons.chevron_right))))]));
  Widget _projects()=>Column(children:[Padding(padding:const EdgeInsets.all(14),child:TextField(onChanged:(v)=>setState(()=>search=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'Buscar projeto...',filled:true,fillColor:AppColors.surface2,border:OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.circular(18))))),Expanded(child:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_refresh,child:GridView.builder(padding:const EdgeInsets.fromLTRB(14,0,14,28),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:.74,crossAxisSpacing:10,mainAxisSpacing:10),itemCount:shown.length,itemBuilder:(_,i)=>_card(shown[i]))))]);
  Widget _card(ProjectRepo p)=>InkWell(onTap:()=>_detail(p),borderRadius:BorderRadius.circular(20),child:Container(clipBehavior:Clip.antiAlias,decoration:BoxDecoration(color:AppColors.surface2,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Image.network(p.socialPreview,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:AppColors.surface,child:Center(child:Text(p.name.characters.first,style:const TextStyle(fontSize:54,fontWeight:FontWeight.w900,color:AppColors.cyan)))))),Padding(padding:const EdgeInsets.all(11),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(p.name,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900))),if(p.isPrivate)const Icon(Icons.lock,size:14,color:AppColors.violet)]),const SizedBox(height:4),Text(p.language,style:const TextStyle(fontSize:12,color:AppColors.cyan,fontWeight:FontWeight.w800)),Text(p.description,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11,color:AppColors.muted))]))])));
  Widget _apks()=>RefreshIndicator(onRefresh:_refresh,child:ListView(padding:const EdgeInsets.all(18),children:[const Text('APKs & Releases',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('APKs publicados em GitHub Releases.',style:TextStyle(color:AppColors.muted)),const SizedBox(height:14),...projects.map((p)=>FutureBuilder<ApkRelease?>(future:github.latestApk(p),builder:(_,s){if(s.connectionState==ConnectionState.waiting)return ListTile(title:Text(p.name),trailing:const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)));final a=s.data;if(a==null)return const SizedBox.shrink();return Card(child:ListTile(leading:const Icon(Icons.android,color:AppColors.green),title:Text(p.name),subtitle:Text('${a.tag} • ${a.name}'),trailing:IconButton(icon:const Icon(Icons.download),onPressed:()=>_open(a.downloadUrl))));}))]));
  Widget _sites()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Sites',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:12),...projects.where((p)=>p.hasSite).map((p)=>Card(child:ListTile(onTap:()=>_open(p.homepage),leading:const Icon(Icons.public,color:AppColors.cyan),title:Text(p.name),subtitle:Text(p.homepage,maxLines:1,overflow:TextOverflow.ellipsis),trailing:const Icon(Icons.open_in_new))))]);
  Widget _settings()=>ListView(padding:const EdgeInsets.all(18),children:[const Text('Ajustes',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.key,color:AppColors.violet),title:const Text('Projetos privados'),subtitle:Text(hasToken?'Token salvo com segurança':'Configure um Fine-grained PAT'),trailing:FilledButton.tonal(onPressed:_tokenDialog,child:Text(hasToken?'Alterar':'Configurar')))),const SizedBox(height:10),Card(child:ListTile(leading:Icon(Icons.terminal,color:termuxOnline?AppColors.green:AppColors.red),title:const Text('Agente Termux'),subtitle:Text(termuxOnline?'Online em 127.0.0.1:8766':'Rode: coucou-agent'))),const SizedBox(height:10),const Card(child:ListTile(leading:Icon(Icons.palette,color:AppColors.cyan),title:Text('Paleta 60-30-10'),subtitle:Text('#0F172A • #1E293B/#111827 • cyan/violeta/verde')))]);
  Future<void> _tokenDialog()async{final c=TextEditingController(text:await github.readToken()??'');if(!mounted)return;await showDialog(context:context,builder:(x)=>AlertDialog(title:const Text('GitHub Fine-grained PAT'),content:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Crie um token com acesso apenas aos repositórios que quer mostrar. Ele fica no armazenamento seguro do Android.'),const SizedBox(height:10),TextField(controller:c,obscureText:true,decoration:const InputDecoration(labelText:'github_pat_...'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Cancelar')),TextButton(onPressed:()async{await github.saveToken('');if(x.mounted)Navigator.pop(x);},child:const Text('Remover')),FilledButton(onPressed:()async{await github.saveToken(c.text);if(x.mounted)Navigator.pop(x);},child:const Text('Salvar'))]));await _refresh();}
  Widget _stat(String a,String b,Color c)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:AppColors.surface2,borderRadius:BorderRadius.circular(18),border:Border.all(color:c.withValues(alpha:.16))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:AppColors.muted)),Text(b,style:TextStyle(fontWeight:FontWeight.w900,color:c))]));
  @override void dispose(){overlaySub?.cancel();FlutterOverlayWindow.disposeOverlayListener();server?.close(force:true);super.dispose();}
}
